#!/bin/bash

# expose environment variables
source .githooks/.env

# expose $FLUTTER_PATH to global so we can call
# dart, flutter commands in processes that don't have access
# like a GIT (GUI) CLIENT
export PATH="$FLUTTER_PATH:$PATH"

cd ..
dart format . -l 120 --fix || { echo 'dart format failed' ; exit 1; }
dart analyze --fatal-infos --fatal-warnings || { echo 'dart analyze failed' ; exit 1; }
