version: 2
enable-beta-ecosystems: true

updates:
  - package-ecosystem: "github-actions"
    directory: "."
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "."
    schedule:
      interval: "weekly"
    versioning-strategy: increase

  - package-ecosystem: "pub"
    directory: "./tools/export_docs"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
