name: ansix
description: AnsiX is an extended ANSI library that provides tools and extensions for Dart & Flutter projects.
version: 0.0.2-prerelease

homepage: https://github.com/nikosportolos/ansix
repository: https://github.com/nikosportolos/ansix
documentation: https://github.com/nikosportolos/ansix
issue_tracker: https://github.com/nikosportolos/ansix/issues

environment:
  sdk: ">=2.19.6 <4.0.0"

dependencies:
  collection: ^1.17.2
  data_class_plugin: ^0.3.1
  meta: ^1.9.1
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.0
  mocktail: ^0.3.0
  test: ^1.24.3
