name: ansix
description: AnsiX is a powerful and easy-to-use library that provides tools and extensions for adding ANSI color and styling support to your Dart & Flutter applications.
version: 0.2.0

homepage: https://github.com/nikosportolos/ansix
repository: https://github.com/nikosportolos/ansix
documentation: https://github.com/nikosportolos/ansix
issue_tracker: https://github.com/nikosportolos/ansix/issues

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  data_class_plugin: ^1.0.4
  meta: ^1.10.0
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.1
  mocktail: ^1.0.0
  tachyon: ^0.0.9
  test: ^1.24.6

screenshots:
  - description: 'This is an AnsiTreeView usage example'
    path: assets/images/treeview/class.png
  - description: 'This is a vertical AnsiGrid usage example'
    path: assets/images/grid/vertical-grid-example.png
  - description: 'This is a horizontal AnsiGrid usage example'
    path: assets/images/grid/horizontal-grid-example.png
  - description: 'This is an OutlinedText usage example with various borders'
    path: assets/images/outlined-text-example-1.png
  - description: 'This is an OutlinedText usage example with auto-wrapped text'
    path: assets/images/outlined-text-example-2.png
  - description: 'Supported ANSI colors'
    path: assets/images/color-tables.png
  - description: 'Supported ANSI text styles'
    path: assets/images/text-styles.png
  - description: 'Supported ANSI border styles'
    path: assets/images/border-styles.png
  - description: 'Supported ANSI border types'
    path: assets/images/border-types.png
  - description: 'This is an animated demonstration of AnsiX text styles'
    path: assets/images/AnsiX.gif

topics:
  - ansi
  - cli
  - console
  - grid
  - treeview
