name: ansix
description: AnsiX is an extended ANSI library that provides tools and extensions for Dart & Flutter projects.
version: 0.0.1+1
publish_to: 'none'

homepage: https://github.com/nikosportolos/ansix
repository: https://github.com/nikosportolos/ansix
documentation: https://github.com/nikosportolos/ansix
issue_tracker: https://github.com/nikosportolos/ansix/issues

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  data_class_plugin: ^0.3.1
  meta: ^1.9.1
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
  mocktail: ^0.3.0
