name: ansix
description: AnsiX is an extended ANSI library that provides tools and extensions for Dart & Flutter projects.
version: 0.0.1+1
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  data_class_plugin: ^0.3.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
