name: ansix
description: AnsiX is a powerful and easy-to-use library that provides tools and extensions for adding ANSI color and styling support to your Dart & Flutter applications.
version: 0.0.6-prerelease

homepage: https://github.com/nikosportolos/ansix
repository: https://github.com/nikosportolos/ansix
documentation: https://github.com/nikosportolos/ansix
issue_tracker: https://github.com/nikosportolos/ansix/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.2
  data_class_plugin: ^1.0.1
  meta: ^1.9.1
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.1
  mocktail: ^0.3.0
  test: ^1.24.3
