part of 'color.dart';

abstract class AnsiColorSet {
  static const Map<String, List<AnsiColor>> map = <String, List<AnsiColor>>{
    'All': all,
    'System': system,
    'Extended': extended,
    'Greyscale': greyscale,
  };

  /// **All colors**
  ///
  /// Includes all 256 available terminal ANSI colors.
  static const List<AnsiColor> all = <AnsiColor>[
    ...system,
    ...extended,
    ...greyscale,
  ];

  /// **System color set**
  ///
  /// The 16 ANSI colors are a set of standardized colors used by early computer terminals,
  /// and are still commonly used today in various terminal applications.
  ///
  /// They consist of eight basic colors and their corresponding "bright" versions.
  static const List<AnsiColor> system = <AnsiColor>[
    AnsiColor.black,
    AnsiColor.maroon,
    AnsiColor.green,
    AnsiColor.olive,
    AnsiColor.navy,
    AnsiColor.magenta,
    AnsiColor.teal,
    AnsiColor.silver,
    AnsiColor.grey,
    AnsiColor.red,
    AnsiColor.lime,
    AnsiColor.yellow,
    AnsiColor.blue,
    AnsiColor.fuchsia,
    AnsiColor.aqua,
    AnsiColor.white,
  ];

  /// **Greyscale color set**
  ///
  /// Greyscale colors are a range of neutral colors that range from black to white, passing through shades of grey.
  ///
  /// They are often used to provide contrast with other colors or to create a subdued, monochromatic look.
  ///
  /// In the context of ANSI terminal colors, greyscale colors are represented by a series of shades ranging
  /// from black to white, with a total of 24 different shades available.
  static const List<AnsiColor> greyscale = <AnsiColor>[
    AnsiColor.grey3,
    AnsiColor.grey7,
    AnsiColor.grey11,
    AnsiColor.grey15,
    AnsiColor.grey19,
    AnsiColor.grey23,
    AnsiColor.grey27,
    AnsiColor.grey30,
    AnsiColor.grey35,
    AnsiColor.grey39,
    AnsiColor.grey42,
    AnsiColor.grey46,
    AnsiColor.grey50,
    AnsiColor.grey54,
    AnsiColor.grey58,
    AnsiColor.grey62,
    AnsiColor.grey66,
    AnsiColor.grey70,
    AnsiColor.grey74,
    AnsiColor.grey78,
    AnsiColor.grey82,
    AnsiColor.grey85,
    AnsiColor.grey89,
    AnsiColor.grey93,
  ];

  /// **Extended color set**
  ///
  /// Extended colors are a range of additional colors beyond the standard 16-color
  /// and 256-color palettes in the ANSI color space.
  ///
  /// They are typically used in modern terminals that support true color or in applications
  /// that can generate 24-bit color codes.
  ///
  /// The extended color range allows for a more extensive and diverse color palette,
  /// enabling users to choose from millions of possible color combinations.
  ///
  /// Each color is represented by an RGB triplet or hexadecimal value, allowing for precise color selection.
  ///
  /// Overall, the extended color range offers greater flexibility and creative freedom when it comes to designing
  /// and displaying text and graphics in a terminal environment.
  static const List<AnsiColor> extended = <AnsiColor>[
    AnsiColor.grey0,
    AnsiColor.navyBlue,
    AnsiColor.darkBlue,
    AnsiColor.blue3,
    AnsiColor.blue2,
    AnsiColor.blue1,
    AnsiColor.darkGreen,
    AnsiColor.deepSkyBlue6,
    AnsiColor.deepSkyBlue7,
    AnsiColor.deepSkyBlue4,
    AnsiColor.dodgerBlue3,
    AnsiColor.dodgerBlue2,
    AnsiColor.green4,
    AnsiColor.springGreen4,
    AnsiColor.turquoise4,
    AnsiColor.deepSkyBlue5,
    AnsiColor.deepSkyBlue3,
    AnsiColor.dodgerBlue1,
    AnsiColor.green2,
    AnsiColor.springGreen6,
    AnsiColor.darkCyan,
    AnsiColor.lightSeaGreen,
    AnsiColor.deepSkyBlue2,
    AnsiColor.deepSkyBlue1,
    AnsiColor.green3,
    AnsiColor.springGreen3,
    AnsiColor.springGreen5,
    AnsiColor.cyan3,
    AnsiColor.darkTurquoise,
    AnsiColor.turquoise2,
    AnsiColor.green1,
    AnsiColor.springGreen2,
    AnsiColor.springGreen1,
    AnsiColor.mediumSpringGreen,
    AnsiColor.cyan2,
    AnsiColor.cyan1,
    AnsiColor.darkRed,
    AnsiColor.deepPink7,
    AnsiColor.purple5,
    AnsiColor.purple4,
    AnsiColor.purple3,
    AnsiColor.blueViolet,
    AnsiColor.orange2,
    AnsiColor.grey37,
    AnsiColor.mediumPurple4,
    AnsiColor.slateBlue2,
    AnsiColor.slateBlue3,
    AnsiColor.royalBlue1,
    AnsiColor.chartreuse4,
    AnsiColor.darkSeaGreen4,
    AnsiColor.paleTurquoise4,
    AnsiColor.steelBlue,
    AnsiColor.steelBlue3,
    AnsiColor.cornflowerBlue,
    AnsiColor.chartreuse6,
    AnsiColor.darkSeaGreen8,
    AnsiColor.cadetBlue,
    AnsiColor.cadetBlue2,
    AnsiColor.skyBlue3,
    AnsiColor.steelBlue4,
    AnsiColor.chartreuse3,
    AnsiColor.paleGreen4,
    AnsiColor.seaGreen3,
    AnsiColor.aquamarine3,
    AnsiColor.mediumTurquoise,
    AnsiColor.steelBlue1,
    AnsiColor.chartreuse2,
    AnsiColor.seaGreen2,
    AnsiColor.seaGreen4,
    AnsiColor.seaGreen1,
    AnsiColor.aquamarine2,
    AnsiColor.darkSlateGray2,
    AnsiColor.darkRed2,
    AnsiColor.deepPink8,
    AnsiColor.darkMagenta,
    AnsiColor.darkMagenta2,
    AnsiColor.darkViolet2,
    AnsiColor.purple,
    AnsiColor.orange4,
    AnsiColor.lightPink4,
    AnsiColor.plum4,
    AnsiColor.mediumPurple3,
    AnsiColor.mediumPurple6,
    AnsiColor.slateBlue1,
    AnsiColor.yellow6,
    AnsiColor.wheat4,
    AnsiColor.grey53,
    AnsiColor.lightSlateGrey,
    AnsiColor.mediumPurple,
    AnsiColor.lightSlateBlue,
    AnsiColor.yellow4,
    AnsiColor.darkOliveGreen5,
    AnsiColor.darkSeaGreen,
    AnsiColor.lightSkyBlue2,
    AnsiColor.lightSkyBlue3,
    AnsiColor.skyBlue2,
    AnsiColor.chartreuse5,
    AnsiColor.darkOliveGreen6,
    AnsiColor.paleGreen3,
    AnsiColor.darkSeaGreen3,
    AnsiColor.darkSlateGray3,
    AnsiColor.skyBlue1,
    AnsiColor.chartreuse1,
    AnsiColor.lightGreen,
    AnsiColor.lightGreen2,
    AnsiColor.paleGreen1,
    AnsiColor.aquamarine1,
    AnsiColor.darkSlateGray1,
    AnsiColor.red3,
    AnsiColor.deepPink4,
    AnsiColor.mediumVioletRed,
    AnsiColor.magenta5,
    AnsiColor.darkViolet,
    AnsiColor.purple2,
    AnsiColor.darkOrange2,
    AnsiColor.indianRed,
    AnsiColor.hotPink4,
    AnsiColor.mediumOrchid3,
    AnsiColor.mediumOrchid,
    AnsiColor.mediumPurple5,
    AnsiColor.darkGoldenrod,
    AnsiColor.lightSalmon3,
    AnsiColor.rosyBrown,
    AnsiColor.grey63,
    AnsiColor.mediumPurple2,
    AnsiColor.mediumPurple1,
    AnsiColor.gold2,
    AnsiColor.darkKhaki,
    AnsiColor.navajoWhite3,
    AnsiColor.grey69,
    AnsiColor.lightSteelBlue3,
    AnsiColor.lightSteelBlue,
    AnsiColor.yellow5,
    AnsiColor.darkOliveGreen3,
    AnsiColor.darkSeaGreen7,
    AnsiColor.darkSeaGreen6,
    AnsiColor.lightCyan3,
    AnsiColor.lightSkyBlue1,
    AnsiColor.greenYellow,
    AnsiColor.darkOliveGreen2,
    AnsiColor.paleGreen2,
    AnsiColor.darkSeaGreen2,
    AnsiColor.darkSeaGreen1,
    AnsiColor.paleTurquoise1,
    AnsiColor.red2,
    AnsiColor.deepPink6,
    AnsiColor.deepPink3,
    AnsiColor.magenta6,
    AnsiColor.magenta3,
    AnsiColor.magenta4,
    AnsiColor.darkOrange3,
    AnsiColor.indianRed4,
    AnsiColor.hotPink3,
    AnsiColor.hotPink2,
    AnsiColor.orchid,
    AnsiColor.mediumOrchid2,
    AnsiColor.orange3,
    AnsiColor.lightSalmon2,
    AnsiColor.lightPink3,
    AnsiColor.pink3,
    AnsiColor.plum3,
    AnsiColor.violet,
    AnsiColor.gold3,
    AnsiColor.lightGoldenrod3,
    AnsiColor.tan,
    AnsiColor.mistyRose3,
    AnsiColor.thistle3,
    AnsiColor.plum2,
    AnsiColor.yellow3,
    AnsiColor.khaki3,
    AnsiColor.lightGoldenrod4,
    AnsiColor.lightYellow3,
    AnsiColor.grey84,
    AnsiColor.lightSteelBlue1,
    AnsiColor.yellow2,
    AnsiColor.darkOliveGreen4,
    AnsiColor.darkOliveGreen1,
    AnsiColor.darkSeaGreen5,
    AnsiColor.honeydew2,
    AnsiColor.lightCyan1,
    AnsiColor.red1,
    AnsiColor.deepPink2,
    AnsiColor.deepPink1,
    AnsiColor.deepPink5,
    AnsiColor.magenta2,
    AnsiColor.magenta1,
    AnsiColor.orangeRed1,
    AnsiColor.indianRed1,
    AnsiColor.indianRed2,
    AnsiColor.hotPink1,
    AnsiColor.hotPink,
    AnsiColor.mediumOrchid1,
    AnsiColor.darkOrange,
    AnsiColor.salmon1,
    AnsiColor.lightCoral,
    AnsiColor.paleVioletRed1,
    AnsiColor.orchid2,
    AnsiColor.orchid1,
    AnsiColor.orange1,
    AnsiColor.sandyBrown,
    AnsiColor.lightSalmon1,
    AnsiColor.lightPink1,
    AnsiColor.pink1,
    AnsiColor.plum1,
    AnsiColor.gold1,
    AnsiColor.lightGoldenrod5,
    AnsiColor.lightGoldenrod2,
    AnsiColor.navajoWhite1,
    AnsiColor.mistyRose1,
    AnsiColor.thistle1,
    AnsiColor.yellow1,
    AnsiColor.lightGoldenrod1,
    AnsiColor.khaki1,
    AnsiColor.wheat1,
    AnsiColor.cornsilk1,
    AnsiColor.grey100,
  ];
}
