name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    defaults:
      run:
        working-directory: .
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: nikosportolos/dart_package@v0.1.0
        with:
          coverage: ${{ inputs.coverage }}
          codecov: true
          codecov_token: ${{ secrets.codecov_token }}
