name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    defaults:
      run:
        working-directory: .
    runs-on: "ubuntu-latest"
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3

      - name: dart-package
        uses: nikosportolos/dart_package@v0.0.1
        with:
          coverage: true
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
