name: CI Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  validate:
    uses: ./.github/workflows/validate.yml
    with:
      working_directory: .
