name: PR Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    defaults:
      run:
        working-directory: .
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: nikosportolos/dart_package@v0.0.5
        with:
          dart_sdk: 3.0.0
