name: Update dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Dependencies
        uses: peiffer-innovations/actions-dart-dependency-updater@v1.1.0
        with:
          merge: true
          pull_request: true
          token: ${{ secrets.GITHUB_TOKEN }}
